const DEFAULT_DISHES = [
  { id: 1,  name: '红烧肉',   emoji: '🍖', desc: '肥而不腻，入口即化',     category: 'meat' },
  { id: 2,  name: '宫保鸡丁', emoji: '🍗', desc: '香辣可口，花生酥脆',     category: 'meat' },
  { id: 3,  name: '糖醋里脊', emoji: '🐖', desc: '外酥里嫩，酸甜适中',     category: 'meat' },
  { id: 4,  name: '鱼香肉丝', emoji: '🐟', desc: '经典川味，下饭神器',     category: 'meat' },
  { id: 5,  name: '回锅肉',   emoji: '🥩', desc: '蒜香浓郁，肥瘦相间',     category: 'meat' },
  { id: 6,  name: '水煮鱼',   emoji: '🌶️', desc: '麻辣鲜香，鱼肉嫩滑',   category: 'meat' },
  { id: 7,  name: '黄焖鸡',   emoji: '🍲', desc: '酱香浓郁，肉质鲜美',     category: 'meat' },
  { id: 8,  name: '东坡肉',   emoji: '🔥', desc: '色泽红亮，酥烂不碎',     category: 'meat' },
  { id: 9,  name: '麻婆豆腐', emoji: '🫘', desc: '麻辣烫香，嫩滑爽口',   category: 'veggie' },
  { id: 10, name: '地三鲜',   emoji: '🍆', desc: '土豆茄子青椒铁三角',     category: 'veggie' },
  { id: 11, name: '手撕包菜', emoji: '🥬', desc: '酸辣脆爽，开胃解腻',     category: 'veggie' },
  { id: 12, name: '番茄炒蛋', emoji: '🍅', desc: '国民家常菜，永远的经典', category: 'veggie' },
  { id: 13, name: '干煸四季豆', emoji: '🌱', desc: '焦香微辣，很有嚼头', category: 'veggie' },
  { id: 14, name: '蒜蓉西兰花', emoji: '🥦', desc: '清爽健康，蒜香四溢',   category: 'veggie' },
  { id: 15, name: '酸辣土豆丝', emoji: '🥔', desc: '清脆爽口，开胃必点',   category: 'veggie' },
  { id: 16, name: '蛋炒饭',   emoji: '🍚', desc: '粒粒分明，朴实美味',     category: 'noodle' },
  { id: 17, name: '兰州拉面', emoji: '🍜', desc: '一清二白三红四绿',         category: 'noodle' },
  { id: 18, name: '饺子',     emoji: '🥟', desc: '好吃不过饺子',             category: 'noodle' },
  { id: 19, name: '麻辣烫',   emoji: '🥘', desc: '万物皆可烫',               category: 'noodle' },
  { id: 20, name: '炒面',     emoji: '🍝', desc: '镬气十足，鲜香弹牙',     category: 'noodle' },
  { id: 21, name: '螺蛳粉',   emoji: '🐌', desc: '闻着臭吃着香',           category: 'noodle' },
  { id: 22, name: '酸辣汤',   emoji: '🥣', desc: '酸辣开胃，暖身首选',     category: 'soup' },
  { id: 23, name: '紫菜蛋花汤', emoji: '🍳', desc: '清淡鲜美，快速出锅',   category: 'soup' },
  { id: 24, name: '排骨莲藕汤', emoji: '🦴', desc: '莲藕粉糯，汤浓味鲜',   category: 'soup' },
  { id: 25, name: '西红柿鸡蛋汤', emoji: '🍲', desc: '酸甜可口，老少皆宜', category: 'soup' },
];

const HOT_DISHES = [
  { name: '小炒肉',       emoji: '🌶️', desc: '香辣下饭',             category: 'meat' },
  { name: '可乐鸡翅',     emoji: '🍗', desc: '甜香入味',             category: 'meat' },
  { name: '酸菜鱼',       emoji: '🐟', desc: '酸爽鲜嫩',             category: 'meat' },
  { name: '红烧排骨',     emoji: '🦴', desc: '酱香浓郁',             category: 'meat' },
  { name: '辣子鸡',       emoji: '🌶️', desc: '麻辣酥香',           category: 'meat' },
  { name: '啤酒鸭',       emoji: '🦆', desc: '酒香四溢',             category: 'meat' },
  { name: '孜然牛肉',     emoji: '🥩', desc: '香气扑鼻',             category: 'meat' },
  { name: '蒜蓉大虾',     emoji: '🦐', desc: '蒜香浓郁',             category: 'meat' },
  { name: '葱爆羊肉',     emoji: '🐑', desc: '葱香肉嫩',             category: 'meat' },
  { name: '京酱肉丝',     emoji: '🥢', desc: '酱香浓郁卷饼吃',     category: 'meat' },
  { name: '粉蒸肉',       emoji: '🍖', desc: '软糯入味',             category: 'meat' },
  { name: '口水鸡',       emoji: '🍗', desc: '麻辣鲜香',             category: 'meat' },
  { name: '卤牛肉',       emoji: '🥩', desc: '酱香入味',             category: 'meat' },
  { name: '脆皮烧肉',     emoji: '🐖', desc: '外脆里嫩',             category: 'meat' },
  { name: '蚝油生菜',     emoji: '🥬', desc: '简单爽口',             category: 'veggie' },
  { name: '醋溜白菜',     emoji: '🥬', desc: '酸甜脆嫩',             category: 'veggie' },
  { name: '凉拌黄瓜',     emoji: '🥒', desc: '清爽解腻',             category: 'veggie' },
  { name: '清炒时蔬',     emoji: '🥬', desc: '健康解腻',             category: 'veggie' },
  { name: '虎皮青椒',     emoji: '🌶️', desc: '焦香软嫩',           category: 'veggie' },
  { name: '荷塘小炒',     emoji: '🌱', desc: '清脆爽口',             category: 'veggie' },
  { name: '蒜茸空心菜',   emoji: '🥬', desc: '蒜香清爽',             category: 'veggie' },
  { name: '红烧冬瓜',     emoji: '🍈', desc: '软烂入味',             category: 'veggie' },
  { name: '香菇青菜',     emoji: '🍄', desc: '鲜美健康',             category: 'veggie' },
  { name: '菠菜拌粉丝',   emoji: '🥬', desc: '爽口凉菜',             category: 'veggie' },
  { name: '糖拌番茄',     emoji: '🍅', desc: '酸甜开胃',             category: 'veggie' },
  { name: '葱油拌面',     emoji: '🍜', desc: '简单快手',             category: 'noodle' },
  { name: '蛋包饭',       emoji: '🍳', desc: '颜值担当',             category: 'noodle' },
  { name: '扬州炒饭',     emoji: '🍚', desc: '粒粒分明',             category: 'noodle' },
  { name: '炸酱面',       emoji: '🍜', desc: '酱香浓郁',             category: 'noodle' },
  { name: '煲仔饭',       emoji: '🍲', desc: '锅巴焦香',             category: 'noodle' },
  { name: '手抓饼',       emoji: '🫓', desc: '层层酥脆',             category: 'noodle' },
  { name: '肉夹馍',       emoji: '🥙', desc: '馍香肉烂',             category: 'noodle' },
  { name: '煎饼果子',     emoji: '🥞', desc: '薄脆鲜香',             category: 'noodle' },
  { name: '热干面',       emoji: '🍜', desc: '芝麻酱香',             category: 'noodle' },
  { name: '担担面',       emoji: '🍜', desc: '麻辣鲜香',             category: 'noodle' },
  { name: '疙瘩汤',       emoji: '🥣', desc: '暖胃家常',             category: 'soup' },
  { name: '冬瓜排骨汤',   emoji: '🦴', desc: '清甜滋补',             category: 'soup' },
  { name: '玉米排骨汤',   emoji: '🌽', desc: '鲜甜可口',             category: 'soup' },
  { name: '菌菇汤',       emoji: '🍄', desc: '鲜美营养',             category: 'soup' },
  { name: '豆腐鱼汤',     emoji: '🐟', desc: '奶白鲜美',             category: 'soup' },
  { name: '绿豆汤',       emoji: '🫘', desc: '清热解暑',             category: 'soup' },
  { name: '银耳莲子汤',   emoji: '🌰', desc: '润肺养颜',             category: 'soup' },
  { name: '萝卜牛腩汤',   emoji: '🐂', desc: '清甜浓郁',             category: 'soup' },
];

export { DEFAULT_DISHES, HOT_DISHES };
